assets: assets
blur_size: 21
center_crop:
- 224
- 224
class_filter_file: false
clickme_data: clickme_datasets/dump_co3d_combined_03_13_2025.npz
correlation_batch_size: 1024
debug: false
display_image_keys: auto
example_image_output_dir: co3d_val_images
experiment_name: co3d_val
file_exclusion_filter: ILSVRC2012_val
file_inclusion_filter: CO3D_ClickMe2
filter_mobile: true
gpu_batch_size: 1024
image_path: /media/data_cifs/projects/prj_video_imagenet/CO3D_ClickMe2
image_shape:
- 256
- 256
mask_dir: co3d_masks
mask_threshold: 0.17
max_clicks: 75
metadata_file: false
metric: spearman
min_clicks: 10
min_subjects: 5
n_jobs: -1
null_iterations: 10
parallel_prepare_maps: true
parallel_save: true
participant_filter: false
percentile_thresh: 50
preprocess_db_data: false
processed_clickme_file: co3d_val_processed.npz
processed_medians: co3d_val_medians.json
remove_string: false
