experiment_name: co3d_val
clickme_data: clickme_datasets/prj_clickmev2_dump_co3d_10_10_2024.npz
processed_clickme_file: "co3d_val_processed.npz"
processed_medians: "co3d_val_medians.json"
example_image_output_dir: "co3d_val_images"
debug: True
assets: "assets"
image_dir: CO3D_ClickMe2
preprocess_db_data: False
blur_size: 21
min_clicks: 10  # Minimum number of clicks for a map to be included
max_clicks: 75 # Maximum number of clicks for a map to be included
min_subjects: 10  # Minimum number of subjects for an image to be included
null_iterations: 10  # For human-to-human ceiling
percentile_thresh: 50  # For median splits
filter_mobile: True
metric: auc  # AUC, crossentropy, spearman, RSA
image_shape: [256, 256]
center_crop: [256, 256]
class_filter_file: False  # Filter classes based on co3d class list
metadata_file: False
mask_dir: co3d_masks  # Directory containing masks for each image
mask_threshold: 0.5  # Max IOU threshold for foreground mask overlap
display_image_keys:
  - mouse/372_41138_81919_renders_00017.png
  - skateboard/55_3249_9602_renders_00041.png
  - couch/617_99940_198836_renders_00040.png
  - microwave/482_69090_134714_renders_00033.png
  - bottle/601_92782_185443_renders_00030.png
  - kite/399_51022_100078_renders_00049.png
  - carrot/405_54110_105495_renders_00039.png
  - banana/49_2817_7682_renders_00025.png
  - parkingmeter/429_60366_116962_renders_00032.png
