assets: assets
blur_size: 21
center_crop:
- 224
- 224
class_filter_file: false
# clickme_data: clickme_datasets/dump_co3d_combined_03_13_2025.npz
clickme_data: /cifs/data/tserre_lrs/projects/projects/prj_video_imagenet/human_clickme_data_processing/clickme_datasets/dump_co3d_05_28_2025_unique.npz
correlation_batch_size: 1024
debug: false
display_image_keys: auto
example_image_output_dir: co3d_train_images
experiment_name: co3d_train
file_exclusion_filter: ILSVRC2012_val
file_inclusion_filter: CO3D_ClickMe2  # CO3D_ClickMe_Training2
filter_mobile: true
gpu_batch_size: 4096
image_path:  /cifs/data/tserre_lrs/projects/projects/prj_video_imagenet/CO3D_ClickMe_Training2/
image_shape:
- 256
- 256
mask_dir: null  # Don't use masks for training right now... Akash TODO
mask_threshold: 0.17
max_clicks: 100000
metadata_file: false
metric: auc
min_clicks: 1
min_subjects: 2
n_jobs: -1
null_iterations: 100
parallel_prepare_maps: true
parallel_save: true  # Fails with lots of images... TODO: Fix
participant_filter: false
percentile_thresh: 50
preprocess_db_data: false
processed_clickme_file: co3d_train_processed.npz
processed_clickmap_bins: co3d_train_clickmap_bins.npy
processed_medians: co3d_train_medians.json
remove_string: false
multi_thresh_gpu: true
time_based_bins: true

