assets: assets
blur_size: 21
center_crop:
- 224
- 224
class_filter_file: false
# clickme_data: clickme_datasets/dump_co3d_combined_03_13_2025.npz
clickme_data: /cifs/data/tserre_lrs/projects/projects/prj_video_imagenet/human_clickme_data_processing/clickme_datasets/dump_co3d_05_28_2025_unique.npz
correlation_batch_size: 128
debug: false
display_image_keys: auto
example_image_output_dir: co3d_constancy_val_images
experiment_name: co3d_constancy_val
file_exclusion_filter: ILSVRC2012_val
file_inclusion_filter: CO3D_Constancy  # CO3D_ClickMe2
filter_mobile: true
gpu_batch_size: 4096
image_path: /cifs/data/tserre_lrs/projects/projects/prj_video_imagenet/PeRFception/data/co3d_v2/clickme_trajectories/
image_shape:
- 256
- 256
mask_dir: null
mask_threshold: 0.
max_clicks: 1000000  # Set to an impossibly high number to keep all maps
metadata_file: false
metric: spearman
min_clicks: 1
min_subjects: 4
n_jobs: -1
null_iterations: 10 # Potentially lower this number for speed up
parallel_prepare_maps: true
parallel_save: true
participant_filter: false
percentile_thresh: 50
preprocess_db_data: false
processed_clickme_file: co3d_constancy_val_processed.npz
processed_clickmap_bins: co3d_constancy_val_clickmap_bins.npy
processed_medians: co3d_constancy_val_medians.json
remove_string: false
multi_thresh_gpu: true
constancy: true
camera_path: clickme_datasets/constancy_params.json
depth_path: /oscar/data/tserre/Users/pzhou10/CVM/onevision/assets/constancy_depths
save_json: true
time_based_bins: true
