assets: assets
blur_size: 21
center_crop:
- 256
- 256
class_filter_file: false
clickme_data: clickme_datasets/train_combined_04_02_2025.npz
correlation_batch_size: 4096
debug: false
display_image_keys: auto
example_image_output_dir: jay_imagenet_train_combined_04_02_2025_images
experiment_name: jay_imagenet_train_04_02_2025
file_exclusion_filter: ILSVRC2012_val
file_inclusion_filter: null
filter_mobile: true
gpu_batch_size: 10000
image_path: /media/data_cifs/projects/prj_video_imagenet/imagenet/ILSVRC/Data/CLS-LOC/train
image_shape:
- 256
- 256
mask_dir: null
mask_threshold: 1
max_clicks: 10000
metadata_file: image_metadata/jay_imagenet_train_0.1_dimensions.npy
metric: spearman
min_clicks: 3
min_subjects: 3
n_jobs: -1
null_iterations: 10
parallel_prepare_maps: true
parallel_save: false
participant_filter: false
percentile_thresh: 50
preprocess_db_data: true
processed_clickme_file: jay_imagenet_train_combined_04_02_2025_processed.npz
processed_medians: jay_imagenet_train_combined_04_02_2025_medians.json
remove_string: imagenet/train/
output_format: "hdf5"
use_cython: true
chunk_size: 100000
batch_size: 50000