assets: assets
blur_size: 21
center_crop:
- 224
- 224
class_filter_file: category_maps/synset_to_co3d.npy
clickme_data: clickme_datasets/val_imagenet_10_17_2024.npz
correlation_batch_size: 8
debug: false
display_image_keys: auto
example_image_output_dir: jay_imagenet_for_co3d_val_0.1_images
experiment_name: jay_imagenet_for_co3d_val_0.1
file_exclusion_filter: false
file_inclusion_filter: ILSVRC2012_val
filter_mobile: true
gpu_batch_size: 4096
image_path: /media/data_cifs/projects/prj_video_imagenet/imagenet/ILSVRC/Data/CLS-LOC/val2
image_shape:
- 256
- 256
mask_dir: null
mask_threshold: 0.
max_clicks: 100000
metadata_file: image_metadata/jay_imagenet_val_0.1_dimensions.npy
metric: auc
min_clicks: 1
min_subjects: 6
n_jobs: -1
null_iterations: 20
parallel_prepare_maps: true
parallel_save: true
participant_filter: false
percentile_thresh: 50
preprocess_db_data: true
processed_clickme_file: jay_imagenet_for_co3d_val_0.1_processed.npz
processed_medians: jay_imagenet_for_co3d_val_0.1_medians.json
remove_string: imagenet/val/
multi_thresh_gpu: true
