experiment_name: jay_imagenet_0.1
clickme_data: clickme_datasets/val_imagenet_09_29_2024.npz
processed_clickme_file: "jay_imagenet_0.1_processed.npz"
processed_medians: "jay_imagenet_0.1_medians.json"
example_image_output_dir: "jay_imagenet_0.1_images"
assets: "assets"
image_dir: ImageNet
preprocess_db_data: True
blur_size: 21
min_clicks: 10  # Minimum number of clicks for a map to be included
max_clicks: 75 # Maximum number of clicks for a map to be included
min_subjects: 5  # Minimum number of subjects for an image to be included
null_iterations: 10
metric: auc  # AUC, crossentropy, spearman, RSA
image_shape: [256, 256]
center_crop: [256, 256]
metadata_file: "image_metadata/imagenet_validation_clickme_dimensions.npy"
display_image_keys:
- ILSVRC2012_val_00009492.JPEG
- ILSVRC2012_val_00032959.JPEG
- ILSVRC2012_val_00048414.JPEG
- ILSVRC2012_val_00033949.JPEG
- ILSVRC2012_val_00011212.JPEG
- ILSVRC2012_val_00044671.JPEG
- ILSVRC2012_val_00021923.JPEG
- ILSVRC2012_val_00043013.JPEG
- ILSVRC2012_val_00007272.JPEG
- ILSVRC2012_val_00011751.JPEG
