assets: assets
blur_size: 21
center_crop:
- 256
- 256
class_filter_file: false
clickme_data: db_dumps/train_combined_02_26_2025.npz
correlation_batch_size: 1024
debug: false
display_image_keys: auto
example_image_output_dir: jay_imagenet_train_combined_02_19_2025_images
experiment_name: jay_imagenet_train_02_19_2025
file_exclusion_filter: false
file_inclusion_filter: false
filter_mobile: true
gpu_batch_size: 1024
image_path: /media/data_cifs/projects/prj_video_imagenet/imagenet/ILSVRC/Data/CLS-LOC/train
image_shape:
- 256
- 256
mask_dir: false
mask_threshold: 1
max_clicks: 10000
metadata_file: image_metadata/jay_imagenet_train_0.1_dimensions.npy
metric: spearman
min_clicks: 3
min_subjects: 3
n_jobs: -1
null_iterations: 10
parallel_prepare_maps: true
parallel_save: true
participant_filter: false
percentile_thresh: 50
preprocess_db_data: true
processed_clickme_file: jay_imagenet_train_combined_02_19_2025_processed.npz
processed_medians: jay_imagenet_train_combined_02_19_2025_medians.json
remove_string: imagenet/train/
