experiment_name: jay_imagenet_for_co3d_val_0.1
clickme_data: clickme_datasets/val_imagenet_10_17_2024.npz
processed_clickme_file: jay_imagenet_for_co3d_val_0.1_processed.npz
processed_medians: jay_imagenet_for_co3d_val_0.1_medians.json
example_image_output_dir: jay_imagenet_for_co3d_val_0.1_images
debug: False
assets: assets
preprocess_db_data: True
blur_size: 21
min_clicks: 10  # Minimum number of clicks for a map to be included
max_clicks: 75 # Maximum number of clicks for a map to be included
min_subjects: 5  # Minimum number of subjects for an image to be included
null_iterations: 10
percentile_thresh: 50  # For median splits
filter_mobile: True
metric: spearman  # AUC, crossentropy, spearman, RSA
image_shape: [256, 256]
center_crop: [256, 256]
class_filter_file: category_maps/synset_to_co3d.npy  # Filter classes based on co3d class list
remove_string: imagenet/val/
image_path: /media/data_cifs/projects/prj_video_imagenet/imagenet/ILSVRC/Data/CLS-LOC/val2
metadata_file: "image_metadata/jay_imagenet_val_0.1_dimensions.npy"  # Per image sizes
file_inclusion_filter: ILSVRC2012_val  # Only include images that match this string
file_exclusion_filter: False  # Exclude images that match this string
mask_dir: False  # Directory containing masks for each image
mask_threshold: 1  # Max IOU threshold for foreground mask overlap
participant_filter: False
display_image_keys: auto   # If "auto", will display the top-10 clicked
parallel_prepare_maps: True
