assets: assets
blur_size: 21
center_crop:
- 224
- 224
class_filter_file: false
clickme_data: clickme_datasets/train_imagenet_10_17_2024.npz
correlation_batch_size: 1024
debug: false
display_image_keys: auto
example_image_output_dir: jay_imagenet_train_0.1_images
experiment_name: jay_imagenet_train_0.1
file_exclusion_filter: false
file_inclusion_filter: false
filter_mobile: true
gpu_batch_size: 1024
image_path: /media/data_cifs/projects/prj_video_imagenet/imagenet/ILSVRC/Data/CLS-LOC/train
image_shape:
- 256
- 256
mask_dir: false
mask_threshold: 1
max_clicks: 100000
metadata_file: image_metadata/jay_imagenet_train_0.1_dimensions.npy
metric: spearman
min_clicks: 10
min_subjects: 3
n_jobs: -1
null_iterations: 10
parallel_prepare_maps: true
participant_filter: false
percentile_thresh: 50
preprocess_db_data: true
processed_clickme_file: jay_imagenet_train_0.1_processed.npz
processed_medians: jay_imagenet_train_0.1_medians.json
remove_string: imagenet/train/
