python prepare_clickmaps.py configs/imgnet_configs_01_15_26/imagenet_co3d_val_oscar.yaml
python prepare_clickmaps.py configs/imgnet_configs_01_15_26/imagenet_train_oscar.yaml
python prepare_clickmaps.py configs/imgnet_configs_01_15_26/imagenet_val_spearman_oscar.yaml
