# python ceiling_floor_estimate.py configs/exp_configs/imagenet_val_oscar_max_5.yaml
# python ceiling_floor_estimate.py configs/exp_configs/imagenet_val_oscar_max_10.yaml
#python ceiling_floor_estimate.py configs/exp_configs/imagenet_val_oscar_max_15.yaml
# python ceiling_floor_estimate.py configs/exp_configs/imagenet_val_oscar_max_20.yaml
python ceiling_floor_estimate.py configs/exp_configs/imagenet_val_oscar_max_25.yaml
# python ceiling_floor_estimate.py configs/exp_configs/imagenet_val_oscar_max_30.yaml

python ceiling_floor_estimate.py configs/balance_exp_configs/imagenet_val_oscar_max_5.yaml
python ceiling_floor_estimate.py configs/balance_exp_configs/imagenet_val_oscar_max_10.yaml
python ceiling_floor_estimate.py configs/balance_exp_configs/imagenet_val_oscar_max_15.yaml
python ceiling_floor_estimate.py configs/balance_exp_configs/imagenet_val_oscar_max_20.yaml